# Generated by Django 3.0.2 on 2020-02-01 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 31, 20, 24, 56, 785643)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='investments_start',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Investments up until now.', max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='savings_start',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Savings up until now.', max_digits=10),
        ),
    ]
