# Generated by Django 3.0.2 on 2020-02-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200131_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='investments_start',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='savings_start',
        ),
    ]
