# Generated by Django 3.0.9 on 2020-10-28 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='story',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='slug placeholder'),
        ),
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.TextField(default='placeholder text'),
            preserve_default=False,
        ),
    ]
