# Generated by Django 3.0.2 on 2020-02-01 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default='2020', max_length=4)),
                ('month', models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='01', max_length=2)),
                ('income', models.DecimalField(decimal_places=2, default=0, help_text='Your total income this month.', max_digits=8)),
                ('savings', models.DecimalField(decimal_places=2, default=0, help_text='The amount you saved this month.', max_digits=8)),
                ('invested', models.DecimalField(decimal_places=2, default=0, help_text='The amount you invested this month.', max_digits=8)),
                ('spent', models.DecimalField(decimal_places=2, default=0, help_text='The amount you spent this month.', max_digits=8)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
