# Generated by Django 3.0.2 on 2020-02-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneytracker', '0003_personmonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investments_start', models.DecimalField(decimal_places=2, default=0, help_text='The amount you have invested up to now.', max_digits=8)),
                ('savings_start', models.DecimalField(decimal_places=2, default=0, help_text='The amount you have saved up to now.', max_digits=8)),
            ],
        ),
        migrations.RenameField(
            model_name='personmonth',
            old_name='invested',
            new_name='investments',
        ),
    ]
